/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses;


import br.com.edfcbz.api.generatedclasses.tables.Address;
import br.com.edfcbz.api.generatedclasses.tables.Availability;
import br.com.edfcbz.api.generatedclasses.tables.City;
import br.com.edfcbz.api.generatedclasses.tables.Country;
import br.com.edfcbz.api.generatedclasses.tables.Courrier;
import br.com.edfcbz.api.generatedclasses.tables.CourrierAvailability;
import br.com.edfcbz.api.generatedclasses.tables.CourrierHasNeighborhood;
import br.com.edfcbz.api.generatedclasses.tables.Cousine;
import br.com.edfcbz.api.generatedclasses.tables.Customer;
import br.com.edfcbz.api.generatedclasses.tables.CustomerHasAddress;
import br.com.edfcbz.api.generatedclasses.tables.Delivery;
import br.com.edfcbz.api.generatedclasses.tables.DeliveryHasStatusDeliveryDomain;
import br.com.edfcbz.api.generatedclasses.tables.Neighborhood;
import br.com.edfcbz.api.generatedclasses.tables.Order;
import br.com.edfcbz.api.generatedclasses.tables.OrderHasProduct;
import br.com.edfcbz.api.generatedclasses.tables.OrderHasStatus;
import br.com.edfcbz.api.generatedclasses.tables.OrderStatusDomain;
import br.com.edfcbz.api.generatedclasses.tables.OrderStore;
import br.com.edfcbz.api.generatedclasses.tables.Product;
import br.com.edfcbz.api.generatedclasses.tables.ProductHasStore;
import br.com.edfcbz.api.generatedclasses.tables.Province;
import br.com.edfcbz.api.generatedclasses.tables.StatusDeliveryDomain;
import br.com.edfcbz.api.generatedclasses.tables.StatusStore;
import br.com.edfcbz.api.generatedclasses.tables.Store;
import br.com.edfcbz.api.generatedclasses.tables.StoreHasAddress;
import br.com.edfcbz.api.generatedclasses.tables.StoreHasCousine;
import br.com.edfcbz.api.generatedclasses.tables.TypeAddress;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Apirest extends SchemaImpl {

    private static final long serialVersionUID = -391981926;

    /**
     * The reference instance of <code>apirest</code>
     */
    public static final Apirest APIREST = new Apirest();

    /**
     * The table <code>apirest.address</code>.
     */
    public final Address ADDRESS = br.com.edfcbz.api.generatedclasses.tables.Address.ADDRESS;

    /**
     * The table <code>apirest.availability</code>.
     */
    public final Availability AVAILABILITY = br.com.edfcbz.api.generatedclasses.tables.Availability.AVAILABILITY;

    /**
     * The table <code>apirest.city</code>.
     */
    public final City CITY = br.com.edfcbz.api.generatedclasses.tables.City.CITY;

    /**
     * The table <code>apirest.country</code>.
     */
    public final Country COUNTRY = br.com.edfcbz.api.generatedclasses.tables.Country.COUNTRY;

    /**
     * The table <code>apirest.courrier</code>.
     */
    public final Courrier COURRIER = br.com.edfcbz.api.generatedclasses.tables.Courrier.COURRIER;

    /**
     * The table <code>apirest.courrier_availability</code>.
     */
    public final CourrierAvailability COURRIER_AVAILABILITY = br.com.edfcbz.api.generatedclasses.tables.CourrierAvailability.COURRIER_AVAILABILITY;

    /**
     * The table <code>apirest.courrier_has_neighborhood</code>.
     */
    public final CourrierHasNeighborhood COURRIER_HAS_NEIGHBORHOOD = br.com.edfcbz.api.generatedclasses.tables.CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD;

    /**
     * The table <code>apirest.cousine</code>.
     */
    public final Cousine COUSINE = br.com.edfcbz.api.generatedclasses.tables.Cousine.COUSINE;

    /**
     * The table <code>apirest.customer</code>.
     */
    public final Customer CUSTOMER = br.com.edfcbz.api.generatedclasses.tables.Customer.CUSTOMER;

    /**
     * The table <code>apirest.customer_has_address</code>.
     */
    public final CustomerHasAddress CUSTOMER_HAS_ADDRESS = br.com.edfcbz.api.generatedclasses.tables.CustomerHasAddress.CUSTOMER_HAS_ADDRESS;

    /**
     * The table <code>apirest.delivery</code>.
     */
    public final Delivery DELIVERY = br.com.edfcbz.api.generatedclasses.tables.Delivery.DELIVERY;

    /**
     * The table <code>apirest.delivery_has_status_delivery_domain</code>.
     */
    public final DeliveryHasStatusDeliveryDomain DELIVERY_HAS_STATUS_DELIVERY_DOMAIN = br.com.edfcbz.api.generatedclasses.tables.DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN;

    /**
     * The table <code>apirest.neighborhood</code>.
     */
    public final Neighborhood NEIGHBORHOOD = br.com.edfcbz.api.generatedclasses.tables.Neighborhood.NEIGHBORHOOD;

    /**
     * The table <code>apirest.order</code>.
     */
    public final Order ORDER = br.com.edfcbz.api.generatedclasses.tables.Order.ORDER;

    /**
     * The table <code>apirest.order_has_product</code>.
     */
    public final OrderHasProduct ORDER_HAS_PRODUCT = br.com.edfcbz.api.generatedclasses.tables.OrderHasProduct.ORDER_HAS_PRODUCT;

    /**
     * The table <code>apirest.order_has_status</code>.
     */
    public final OrderHasStatus ORDER_HAS_STATUS = br.com.edfcbz.api.generatedclasses.tables.OrderHasStatus.ORDER_HAS_STATUS;

    /**
     * The table <code>apirest.order_status_domain</code>.
     */
    public final OrderStatusDomain ORDER_STATUS_DOMAIN = br.com.edfcbz.api.generatedclasses.tables.OrderStatusDomain.ORDER_STATUS_DOMAIN;

    /**
     * The table <code>apirest.order_store</code>.
     */
    public final OrderStore ORDER_STORE = br.com.edfcbz.api.generatedclasses.tables.OrderStore.ORDER_STORE;

    /**
     * The table <code>apirest.product</code>.
     */
    public final Product PRODUCT = br.com.edfcbz.api.generatedclasses.tables.Product.PRODUCT;

    /**
     * The table <code>apirest.product_has_store</code>.
     */
    public final ProductHasStore PRODUCT_HAS_STORE = br.com.edfcbz.api.generatedclasses.tables.ProductHasStore.PRODUCT_HAS_STORE;

    /**
     * The table <code>apirest.province</code>.
     */
    public final Province PROVINCE = br.com.edfcbz.api.generatedclasses.tables.Province.PROVINCE;

    /**
     * The table <code>apirest.status_delivery_domain</code>.
     */
    public final StatusDeliveryDomain STATUS_DELIVERY_DOMAIN = br.com.edfcbz.api.generatedclasses.tables.StatusDeliveryDomain.STATUS_DELIVERY_DOMAIN;

    /**
     * The table <code>apirest.status_store</code>.
     */
    public final StatusStore STATUS_STORE = br.com.edfcbz.api.generatedclasses.tables.StatusStore.STATUS_STORE;

    /**
     * The table <code>apirest.store</code>.
     */
    public final Store STORE = br.com.edfcbz.api.generatedclasses.tables.Store.STORE;

    /**
     * The table <code>apirest.store_has_address</code>.
     */
    public final StoreHasAddress STORE_HAS_ADDRESS = br.com.edfcbz.api.generatedclasses.tables.StoreHasAddress.STORE_HAS_ADDRESS;

    /**
     * The table <code>apirest.store_has_cousine</code>.
     */
    public final StoreHasCousine STORE_HAS_COUSINE = br.com.edfcbz.api.generatedclasses.tables.StoreHasCousine.STORE_HAS_COUSINE;

    /**
     * The table <code>apirest.type_address</code>.
     */
    public final TypeAddress TYPE_ADDRESS = br.com.edfcbz.api.generatedclasses.tables.TypeAddress.TYPE_ADDRESS;

    /**
     * No further instances allowed
     */
    private Apirest() {
        super("apirest", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Availability.AVAILABILITY,
            City.CITY,
            Country.COUNTRY,
            Courrier.COURRIER,
            CourrierAvailability.COURRIER_AVAILABILITY,
            CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD,
            Cousine.COUSINE,
            Customer.CUSTOMER,
            CustomerHasAddress.CUSTOMER_HAS_ADDRESS,
            Delivery.DELIVERY,
            DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN,
            Neighborhood.NEIGHBORHOOD,
            Order.ORDER,
            OrderHasProduct.ORDER_HAS_PRODUCT,
            OrderHasStatus.ORDER_HAS_STATUS,
            OrderStatusDomain.ORDER_STATUS_DOMAIN,
            OrderStore.ORDER_STORE,
            Product.PRODUCT,
            ProductHasStore.PRODUCT_HAS_STORE,
            Province.PROVINCE,
            StatusDeliveryDomain.STATUS_DELIVERY_DOMAIN,
            StatusStore.STATUS_STORE,
            Store.STORE,
            StoreHasAddress.STORE_HAS_ADDRESS,
            StoreHasCousine.STORE_HAS_COUSINE,
            TypeAddress.TYPE_ADDRESS);
    }
}
