/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses;


import br.com.edfcbz.api.generatedclasses.tables.Address;
import br.com.edfcbz.api.generatedclasses.tables.Availability;
import br.com.edfcbz.api.generatedclasses.tables.City;
import br.com.edfcbz.api.generatedclasses.tables.Country;
import br.com.edfcbz.api.generatedclasses.tables.Courrier;
import br.com.edfcbz.api.generatedclasses.tables.CourrierAvailability;
import br.com.edfcbz.api.generatedclasses.tables.CourrierHasNeighborhood;
import br.com.edfcbz.api.generatedclasses.tables.Cousine;
import br.com.edfcbz.api.generatedclasses.tables.Customer;
import br.com.edfcbz.api.generatedclasses.tables.CustomerHasAddress;
import br.com.edfcbz.api.generatedclasses.tables.Delivery;
import br.com.edfcbz.api.generatedclasses.tables.DeliveryHasStatusDeliveryDomain;
import br.com.edfcbz.api.generatedclasses.tables.Neighborhood;
import br.com.edfcbz.api.generatedclasses.tables.Order;
import br.com.edfcbz.api.generatedclasses.tables.OrderHasProduct;
import br.com.edfcbz.api.generatedclasses.tables.OrderHasStatus;
import br.com.edfcbz.api.generatedclasses.tables.OrderStatusDomain;
import br.com.edfcbz.api.generatedclasses.tables.OrderStore;
import br.com.edfcbz.api.generatedclasses.tables.Product;
import br.com.edfcbz.api.generatedclasses.tables.ProductHasStore;
import br.com.edfcbz.api.generatedclasses.tables.Province;
import br.com.edfcbz.api.generatedclasses.tables.StatusDeliveryDomain;
import br.com.edfcbz.api.generatedclasses.tables.StatusStore;
import br.com.edfcbz.api.generatedclasses.tables.Store;
import br.com.edfcbz.api.generatedclasses.tables.StoreHasAddress;
import br.com.edfcbz.api.generatedclasses.tables.StoreHasCousine;
import br.com.edfcbz.api.generatedclasses.tables.TypeAddress;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>apirest</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADDRESS_FK_ADDRESS_CITY1_IDX = Indexes0.ADDRESS_FK_ADDRESS_CITY1_IDX;
    public static final Index ADDRESS_FK_ADDRESS_NEIGHBORHOOD1_IDX = Indexes0.ADDRESS_FK_ADDRESS_NEIGHBORHOOD1_IDX;
    public static final Index ADDRESS_PRIMARY = Indexes0.ADDRESS_PRIMARY;
    public static final Index AVAILABILITY_PRIMARY = Indexes0.AVAILABILITY_PRIMARY;
    public static final Index CITY_FK_CITY_PROVINCE1_IDX = Indexes0.CITY_FK_CITY_PROVINCE1_IDX;
    public static final Index CITY_PRIMARY = Indexes0.CITY_PRIMARY;
    public static final Index COUNTRY_PRIMARY = Indexes0.COUNTRY_PRIMARY;
    public static final Index COURRIER_FK_COURRIER_ADDRESS1_IDX = Indexes0.COURRIER_FK_COURRIER_ADDRESS1_IDX;
    public static final Index COURRIER_PRIMARY = Indexes0.COURRIER_PRIMARY;
    public static final Index COURRIER_AVAILABILITY_FK_COURRIER_HAS_AVAILABILITY_AVAILABILITY1_IDX = Indexes0.COURRIER_AVAILABILITY_FK_COURRIER_HAS_AVAILABILITY_AVAILABILITY1_IDX;
    public static final Index COURRIER_AVAILABILITY_FK_COURRIER_HAS_AVAILABILITY_COURRIER1_IDX = Indexes0.COURRIER_AVAILABILITY_FK_COURRIER_HAS_AVAILABILITY_COURRIER1_IDX;
    public static final Index COURRIER_AVAILABILITY_PRIMARY = Indexes0.COURRIER_AVAILABILITY_PRIMARY;
    public static final Index COURRIER_HAS_NEIGHBORHOOD_FK_COURRIER_HAS_NEIGHBORHOOD_COURRIER1_IDX = Indexes0.COURRIER_HAS_NEIGHBORHOOD_FK_COURRIER_HAS_NEIGHBORHOOD_COURRIER1_IDX;
    public static final Index COURRIER_HAS_NEIGHBORHOOD_FK_COURRIER_HAS_NEIGHBORHOOD_NEIGHBORHOOD1_IDX = Indexes0.COURRIER_HAS_NEIGHBORHOOD_FK_COURRIER_HAS_NEIGHBORHOOD_NEIGHBORHOOD1_IDX;
    public static final Index COURRIER_HAS_NEIGHBORHOOD_PRIMARY = Indexes0.COURRIER_HAS_NEIGHBORHOOD_PRIMARY;
    public static final Index COUSINE_PRIMARY = Indexes0.COUSINE_PRIMARY;
    public static final Index CUSTOMER_ID_UNIQUE = Indexes0.CUSTOMER_ID_UNIQUE;
    public static final Index CUSTOMER_PRIMARY = Indexes0.CUSTOMER_PRIMARY;
    public static final Index CUSTOMER_HAS_ADDRESS_FK_CUSTOMER_HAS_ADDRESS_ADDRESS1_IDX = Indexes0.CUSTOMER_HAS_ADDRESS_FK_CUSTOMER_HAS_ADDRESS_ADDRESS1_IDX;
    public static final Index CUSTOMER_HAS_ADDRESS_FK_CUSTOMER_HAS_ADDRESS_CUSTOMER1_IDX = Indexes0.CUSTOMER_HAS_ADDRESS_FK_CUSTOMER_HAS_ADDRESS_CUSTOMER1_IDX;
    public static final Index CUSTOMER_HAS_ADDRESS_FK_CUSTOMER_HAS_ADDRESS_TYPE_ADDRESS1_IDX = Indexes0.CUSTOMER_HAS_ADDRESS_FK_CUSTOMER_HAS_ADDRESS_TYPE_ADDRESS1_IDX;
    public static final Index CUSTOMER_HAS_ADDRESS_PRIMARY = Indexes0.CUSTOMER_HAS_ADDRESS_PRIMARY;
    public static final Index DELIVERY_FK_DELIVERY_COURRIER1_IDX = Indexes0.DELIVERY_FK_DELIVERY_COURRIER1_IDX;
    public static final Index DELIVERY_PRIMARY = Indexes0.DELIVERY_PRIMARY;
    public static final Index DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_FK_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_DELIVERY1_IDX = Indexes0.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_FK_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_DELIVERY1_IDX;
    public static final Index DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_FK_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_STATUS_DELIVERY_DOMA_IDX = Indexes0.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_FK_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_STATUS_DELIVERY_DOMA_IDX;
    public static final Index DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_PRIMARY = Indexes0.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_PRIMARY;
    public static final Index NEIGHBORHOOD_PRIMARY = Indexes0.NEIGHBORHOOD_PRIMARY;
    public static final Index ORDER_FK_ORDER_CUSTOMER1_IDX = Indexes0.ORDER_FK_ORDER_CUSTOMER1_IDX;
    public static final Index ORDER_FK_ORDER_DELIVERY1_IDX = Indexes0.ORDER_FK_ORDER_DELIVERY1_IDX;
    public static final Index ORDER_ID_UNIQUE = Indexes0.ORDER_ID_UNIQUE;
    public static final Index ORDER_PRIMARY = Indexes0.ORDER_PRIMARY;
    public static final Index ORDER_HAS_PRODUCT_FK_ORDER_HAS_PRODUCT_ORDER1_IDX = Indexes0.ORDER_HAS_PRODUCT_FK_ORDER_HAS_PRODUCT_ORDER1_IDX;
    public static final Index ORDER_HAS_PRODUCT_FK_ORDER_HAS_PRODUCT_PRODUCT1_IDX = Indexes0.ORDER_HAS_PRODUCT_FK_ORDER_HAS_PRODUCT_PRODUCT1_IDX;
    public static final Index ORDER_HAS_PRODUCT_PRIMARY = Indexes0.ORDER_HAS_PRODUCT_PRIMARY;
    public static final Index ORDER_HAS_STATUS_FK_ORDER_HAS_ORDER_STATUS_DOMAIN_ORDER1_IDX = Indexes0.ORDER_HAS_STATUS_FK_ORDER_HAS_ORDER_STATUS_DOMAIN_ORDER1_IDX;
    public static final Index ORDER_HAS_STATUS_FK_ORDER_HAS_ORDER_STATUS_DOMAIN_ORDER_STATUS_DOMAIN1_IDX = Indexes0.ORDER_HAS_STATUS_FK_ORDER_HAS_ORDER_STATUS_DOMAIN_ORDER_STATUS_DOMAIN1_IDX;
    public static final Index ORDER_HAS_STATUS_PRIMARY = Indexes0.ORDER_HAS_STATUS_PRIMARY;
    public static final Index ORDER_STATUS_DOMAIN_PRIMARY = Indexes0.ORDER_STATUS_DOMAIN_PRIMARY;
    public static final Index ORDER_STORE_FK_ORDER_HAS_STORE_ORDER1_IDX = Indexes0.ORDER_STORE_FK_ORDER_HAS_STORE_ORDER1_IDX;
    public static final Index ORDER_STORE_FK_ORDER_HAS_STORE_STORE1_IDX = Indexes0.ORDER_STORE_FK_ORDER_HAS_STORE_STORE1_IDX;
    public static final Index ORDER_STORE_PRIMARY = Indexes0.ORDER_STORE_PRIMARY;
    public static final Index PRODUCT_PRIMARY = Indexes0.PRODUCT_PRIMARY;
    public static final Index PRODUCT_HAS_STORE_FK_PRODUCT_HAS_STORE_PRODUCT1_IDX = Indexes0.PRODUCT_HAS_STORE_FK_PRODUCT_HAS_STORE_PRODUCT1_IDX;
    public static final Index PRODUCT_HAS_STORE_FK_PRODUCT_HAS_STORE_STORE1_IDX = Indexes0.PRODUCT_HAS_STORE_FK_PRODUCT_HAS_STORE_STORE1_IDX;
    public static final Index PRODUCT_HAS_STORE_PRIMARY = Indexes0.PRODUCT_HAS_STORE_PRIMARY;
    public static final Index PROVINCE_FK_PROVINCE_COUNTRY1_IDX = Indexes0.PROVINCE_FK_PROVINCE_COUNTRY1_IDX;
    public static final Index PROVINCE_PRIMARY = Indexes0.PROVINCE_PRIMARY;
    public static final Index STATUS_DELIVERY_DOMAIN_PRIMARY = Indexes0.STATUS_DELIVERY_DOMAIN_PRIMARY;
    public static final Index STATUS_STORE_PRIMARY = Indexes0.STATUS_STORE_PRIMARY;
    public static final Index STORE_FK_STORE_STATUS_STORE1_IDX = Indexes0.STORE_FK_STORE_STATUS_STORE1_IDX;
    public static final Index STORE_PRIMARY = Indexes0.STORE_PRIMARY;
    public static final Index STORE_HAS_ADDRESS_FK_STORE_HAS_ADDRESS_ADDRESS1_IDX = Indexes0.STORE_HAS_ADDRESS_FK_STORE_HAS_ADDRESS_ADDRESS1_IDX;
    public static final Index STORE_HAS_ADDRESS_FK_STORE_HAS_ADDRESS_STORE1_IDX = Indexes0.STORE_HAS_ADDRESS_FK_STORE_HAS_ADDRESS_STORE1_IDX;
    public static final Index STORE_HAS_ADDRESS_PRIMARY = Indexes0.STORE_HAS_ADDRESS_PRIMARY;
    public static final Index STORE_HAS_COUSINE_FK_STORE_HAS_COUSINE_COUSINE1_IDX = Indexes0.STORE_HAS_COUSINE_FK_STORE_HAS_COUSINE_COUSINE1_IDX;
    public static final Index STORE_HAS_COUSINE_FK_STORE_HAS_COUSINE_STORE1_IDX = Indexes0.STORE_HAS_COUSINE_FK_STORE_HAS_COUSINE_STORE1_IDX;
    public static final Index STORE_HAS_COUSINE_PRIMARY = Indexes0.STORE_HAS_COUSINE_PRIMARY;
    public static final Index TYPE_ADDRESS_PRIMARY = Indexes0.TYPE_ADDRESS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADDRESS_FK_ADDRESS_CITY1_IDX = Internal.createIndex("fk_address_city1_idx", Address.ADDRESS, new OrderField[] { Address.ADDRESS.CITY_ID }, false);
        public static Index ADDRESS_FK_ADDRESS_NEIGHBORHOOD1_IDX = Internal.createIndex("fk_address_neighborhood1_idx", Address.ADDRESS, new OrderField[] { Address.ADDRESS.NEIGHBORHOOD_ID }, false);
        public static Index ADDRESS_PRIMARY = Internal.createIndex("PRIMARY", Address.ADDRESS, new OrderField[] { Address.ADDRESS.ID, Address.ADDRESS.CITY_ID, Address.ADDRESS.NEIGHBORHOOD_ID }, true);
        public static Index AVAILABILITY_PRIMARY = Internal.createIndex("PRIMARY", Availability.AVAILABILITY, new OrderField[] { Availability.AVAILABILITY.ID }, true);
        public static Index CITY_FK_CITY_PROVINCE1_IDX = Internal.createIndex("fk_city_province1_idx", City.CITY, new OrderField[] { City.CITY.PROVINCE_ID }, false);
        public static Index CITY_PRIMARY = Internal.createIndex("PRIMARY", City.CITY, new OrderField[] { City.CITY.ID, City.CITY.PROVINCE_ID, City.CITY.NAME }, true);
        public static Index COUNTRY_PRIMARY = Internal.createIndex("PRIMARY", Country.COUNTRY, new OrderField[] { Country.COUNTRY.ID }, true);
        public static Index COURRIER_FK_COURRIER_ADDRESS1_IDX = Internal.createIndex("fk_courrier_address1_idx", Courrier.COURRIER, new OrderField[] { Courrier.COURRIER.ADDRESS_ID }, false);
        public static Index COURRIER_PRIMARY = Internal.createIndex("PRIMARY", Courrier.COURRIER, new OrderField[] { Courrier.COURRIER.ID, Courrier.COURRIER.ADDRESS_ID }, true);
        public static Index COURRIER_AVAILABILITY_FK_COURRIER_HAS_AVAILABILITY_AVAILABILITY1_IDX = Internal.createIndex("fk_courrier_has_availability_availability1_idx", CourrierAvailability.COURRIER_AVAILABILITY, new OrderField[] { CourrierAvailability.COURRIER_AVAILABILITY.AVAILABILITY_ID }, false);
        public static Index COURRIER_AVAILABILITY_FK_COURRIER_HAS_AVAILABILITY_COURRIER1_IDX = Internal.createIndex("fk_courrier_has_availability_courrier1_idx", CourrierAvailability.COURRIER_AVAILABILITY, new OrderField[] { CourrierAvailability.COURRIER_AVAILABILITY.COURRIER_ID }, false);
        public static Index COURRIER_AVAILABILITY_PRIMARY = Internal.createIndex("PRIMARY", CourrierAvailability.COURRIER_AVAILABILITY, new OrderField[] { CourrierAvailability.COURRIER_AVAILABILITY.ID }, true);
        public static Index COURRIER_HAS_NEIGHBORHOOD_FK_COURRIER_HAS_NEIGHBORHOOD_COURRIER1_IDX = Internal.createIndex("fk_courrier_has_neighborhood_courrier1_idx", CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD, new OrderField[] { CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD.COURRIER_ID }, false);
        public static Index COURRIER_HAS_NEIGHBORHOOD_FK_COURRIER_HAS_NEIGHBORHOOD_NEIGHBORHOOD1_IDX = Internal.createIndex("fk_courrier_has_neighborhood_neighborhood1_idx", CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD, new OrderField[] { CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD.NEIGHBORHOOD_ID }, false);
        public static Index COURRIER_HAS_NEIGHBORHOOD_PRIMARY = Internal.createIndex("PRIMARY", CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD, new OrderField[] { CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD.ID }, true);
        public static Index COUSINE_PRIMARY = Internal.createIndex("PRIMARY", Cousine.COUSINE, new OrderField[] { Cousine.COUSINE.ID }, true);
        public static Index CUSTOMER_ID_UNIQUE = Internal.createIndex("id_UNIQUE", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
        public static Index CUSTOMER_PRIMARY = Internal.createIndex("PRIMARY", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
        public static Index CUSTOMER_HAS_ADDRESS_FK_CUSTOMER_HAS_ADDRESS_ADDRESS1_IDX = Internal.createIndex("fk_customer_has_address_address1_idx", CustomerHasAddress.CUSTOMER_HAS_ADDRESS, new OrderField[] { CustomerHasAddress.CUSTOMER_HAS_ADDRESS.ADDRESS_ID }, false);
        public static Index CUSTOMER_HAS_ADDRESS_FK_CUSTOMER_HAS_ADDRESS_CUSTOMER1_IDX = Internal.createIndex("fk_customer_has_address_customer1_idx", CustomerHasAddress.CUSTOMER_HAS_ADDRESS, new OrderField[] { CustomerHasAddress.CUSTOMER_HAS_ADDRESS.CUSTOMER_ID }, false);
        public static Index CUSTOMER_HAS_ADDRESS_FK_CUSTOMER_HAS_ADDRESS_TYPE_ADDRESS1_IDX = Internal.createIndex("fk_customer_has_address_type_address1_idx", CustomerHasAddress.CUSTOMER_HAS_ADDRESS, new OrderField[] { CustomerHasAddress.CUSTOMER_HAS_ADDRESS.TYPE_ADDRESS_ID }, false);
        public static Index CUSTOMER_HAS_ADDRESS_PRIMARY = Internal.createIndex("PRIMARY", CustomerHasAddress.CUSTOMER_HAS_ADDRESS, new OrderField[] { CustomerHasAddress.CUSTOMER_HAS_ADDRESS.ID }, true);
        public static Index DELIVERY_FK_DELIVERY_COURRIER1_IDX = Internal.createIndex("fk_delivery_courrier1_idx", Delivery.DELIVERY, new OrderField[] { Delivery.DELIVERY.COURRIER_ID }, false);
        public static Index DELIVERY_PRIMARY = Internal.createIndex("PRIMARY", Delivery.DELIVERY, new OrderField[] { Delivery.DELIVERY.ID }, true);
        public static Index DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_FK_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_DELIVERY1_IDX = Internal.createIndex("fk_delivery_has_status_delivery_domain_delivery1_idx", DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN, new OrderField[] { DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN.DELIVERY_ID }, false);
        public static Index DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_FK_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_STATUS_DELIVERY_DOMA_IDX = Internal.createIndex("fk_delivery_has_status_delivery_domain_status_delivery_doma_idx", DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN, new OrderField[] { DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN.STATUS_DELIVERY_DOMAIN_ID }, false);
        public static Index DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_PRIMARY = Internal.createIndex("PRIMARY", DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN, new OrderField[] { DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN.ID }, true);
        public static Index NEIGHBORHOOD_PRIMARY = Internal.createIndex("PRIMARY", Neighborhood.NEIGHBORHOOD, new OrderField[] { Neighborhood.NEIGHBORHOOD.ID }, true);
        public static Index ORDER_FK_ORDER_CUSTOMER1_IDX = Internal.createIndex("fk_order_customer1_idx", Order.ORDER, new OrderField[] { Order.ORDER.CUSTOMER_ID }, false);
        public static Index ORDER_FK_ORDER_DELIVERY1_IDX = Internal.createIndex("fk_order_delivery1_idx", Order.ORDER, new OrderField[] { Order.ORDER.DELIVERY_ID }, false);
        public static Index ORDER_ID_UNIQUE = Internal.createIndex("id_UNIQUE", Order.ORDER, new OrderField[] { Order.ORDER.ID }, true);
        public static Index ORDER_PRIMARY = Internal.createIndex("PRIMARY", Order.ORDER, new OrderField[] { Order.ORDER.ID }, true);
        public static Index ORDER_HAS_PRODUCT_FK_ORDER_HAS_PRODUCT_ORDER1_IDX = Internal.createIndex("fk_order_has_product_order1_idx", OrderHasProduct.ORDER_HAS_PRODUCT, new OrderField[] { OrderHasProduct.ORDER_HAS_PRODUCT.ORDER_ID }, false);
        public static Index ORDER_HAS_PRODUCT_FK_ORDER_HAS_PRODUCT_PRODUCT1_IDX = Internal.createIndex("fk_order_has_product_product1_idx", OrderHasProduct.ORDER_HAS_PRODUCT, new OrderField[] { OrderHasProduct.ORDER_HAS_PRODUCT.PRODUCT_ID }, false);
        public static Index ORDER_HAS_PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", OrderHasProduct.ORDER_HAS_PRODUCT, new OrderField[] { OrderHasProduct.ORDER_HAS_PRODUCT.ID }, true);
        public static Index ORDER_HAS_STATUS_FK_ORDER_HAS_ORDER_STATUS_DOMAIN_ORDER1_IDX = Internal.createIndex("fk_order_has_order_status_domain_order1_idx", OrderHasStatus.ORDER_HAS_STATUS, new OrderField[] { OrderHasStatus.ORDER_HAS_STATUS.ORDER_ID }, false);
        public static Index ORDER_HAS_STATUS_FK_ORDER_HAS_ORDER_STATUS_DOMAIN_ORDER_STATUS_DOMAIN1_IDX = Internal.createIndex("fk_order_has_order_status_domain_order_status_domain1_idx", OrderHasStatus.ORDER_HAS_STATUS, new OrderField[] { OrderHasStatus.ORDER_HAS_STATUS.ORDER_STATUS_DOMAIN_ID }, false);
        public static Index ORDER_HAS_STATUS_PRIMARY = Internal.createIndex("PRIMARY", OrderHasStatus.ORDER_HAS_STATUS, new OrderField[] { OrderHasStatus.ORDER_HAS_STATUS.ID }, true);
        public static Index ORDER_STATUS_DOMAIN_PRIMARY = Internal.createIndex("PRIMARY", OrderStatusDomain.ORDER_STATUS_DOMAIN, new OrderField[] { OrderStatusDomain.ORDER_STATUS_DOMAIN.ID }, true);
        public static Index ORDER_STORE_FK_ORDER_HAS_STORE_ORDER1_IDX = Internal.createIndex("fk_order_has_store_order1_idx", OrderStore.ORDER_STORE, new OrderField[] { OrderStore.ORDER_STORE.ORDER_ID }, false);
        public static Index ORDER_STORE_FK_ORDER_HAS_STORE_STORE1_IDX = Internal.createIndex("fk_order_has_store_store1_idx", OrderStore.ORDER_STORE, new OrderField[] { OrderStore.ORDER_STORE.STORE_ID }, false);
        public static Index ORDER_STORE_PRIMARY = Internal.createIndex("PRIMARY", OrderStore.ORDER_STORE, new OrderField[] { OrderStore.ORDER_STORE.ID }, true);
        public static Index PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", Product.PRODUCT, new OrderField[] { Product.PRODUCT.ID }, true);
        public static Index PRODUCT_HAS_STORE_FK_PRODUCT_HAS_STORE_PRODUCT1_IDX = Internal.createIndex("fk_product_has_store_product1_idx", ProductHasStore.PRODUCT_HAS_STORE, new OrderField[] { ProductHasStore.PRODUCT_HAS_STORE.PRODUCT_ID }, false);
        public static Index PRODUCT_HAS_STORE_FK_PRODUCT_HAS_STORE_STORE1_IDX = Internal.createIndex("fk_product_has_store_store1_idx", ProductHasStore.PRODUCT_HAS_STORE, new OrderField[] { ProductHasStore.PRODUCT_HAS_STORE.STORE_ID }, false);
        public static Index PRODUCT_HAS_STORE_PRIMARY = Internal.createIndex("PRIMARY", ProductHasStore.PRODUCT_HAS_STORE, new OrderField[] { ProductHasStore.PRODUCT_HAS_STORE.ID }, true);
        public static Index PROVINCE_FK_PROVINCE_COUNTRY1_IDX = Internal.createIndex("fk_province_country1_idx", Province.PROVINCE, new OrderField[] { Province.PROVINCE.COUNTRY_ID }, false);
        public static Index PROVINCE_PRIMARY = Internal.createIndex("PRIMARY", Province.PROVINCE, new OrderField[] { Province.PROVINCE.ID }, true);
        public static Index STATUS_DELIVERY_DOMAIN_PRIMARY = Internal.createIndex("PRIMARY", StatusDeliveryDomain.STATUS_DELIVERY_DOMAIN, new OrderField[] { StatusDeliveryDomain.STATUS_DELIVERY_DOMAIN.ID }, true);
        public static Index STATUS_STORE_PRIMARY = Internal.createIndex("PRIMARY", StatusStore.STATUS_STORE, new OrderField[] { StatusStore.STATUS_STORE.ID }, true);
        public static Index STORE_FK_STORE_STATUS_STORE1_IDX = Internal.createIndex("fk_store_status_store1_idx", Store.STORE, new OrderField[] { Store.STORE.STATUS_STORE_ID }, false);
        public static Index STORE_PRIMARY = Internal.createIndex("PRIMARY", Store.STORE, new OrderField[] { Store.STORE.ID, Store.STORE.STATUS_STORE_ID }, true);
        public static Index STORE_HAS_ADDRESS_FK_STORE_HAS_ADDRESS_ADDRESS1_IDX = Internal.createIndex("fk_store_has_address_address1_idx", StoreHasAddress.STORE_HAS_ADDRESS, new OrderField[] { StoreHasAddress.STORE_HAS_ADDRESS.ADDRESS_ID }, false);
        public static Index STORE_HAS_ADDRESS_FK_STORE_HAS_ADDRESS_STORE1_IDX = Internal.createIndex("fk_store_has_address_store1_idx", StoreHasAddress.STORE_HAS_ADDRESS, new OrderField[] { StoreHasAddress.STORE_HAS_ADDRESS.STORE_ID }, false);
        public static Index STORE_HAS_ADDRESS_PRIMARY = Internal.createIndex("PRIMARY", StoreHasAddress.STORE_HAS_ADDRESS, new OrderField[] { StoreHasAddress.STORE_HAS_ADDRESS.ID }, true);
        public static Index STORE_HAS_COUSINE_FK_STORE_HAS_COUSINE_COUSINE1_IDX = Internal.createIndex("fk_store_has_cousine_cousine1_idx", StoreHasCousine.STORE_HAS_COUSINE, new OrderField[] { StoreHasCousine.STORE_HAS_COUSINE.COUSINE_ID }, false);
        public static Index STORE_HAS_COUSINE_FK_STORE_HAS_COUSINE_STORE1_IDX = Internal.createIndex("fk_store_has_cousine_store1_idx", StoreHasCousine.STORE_HAS_COUSINE, new OrderField[] { StoreHasCousine.STORE_HAS_COUSINE.STOREID }, false);
        public static Index STORE_HAS_COUSINE_PRIMARY = Internal.createIndex("PRIMARY", StoreHasCousine.STORE_HAS_COUSINE, new OrderField[] { StoreHasCousine.STORE_HAS_COUSINE.ID }, true);
        public static Index TYPE_ADDRESS_PRIMARY = Internal.createIndex("PRIMARY", TypeAddress.TYPE_ADDRESS, new OrderField[] { TypeAddress.TYPE_ADDRESS.ID }, true);
    }
}
