/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses;


import br.com.edfcbz.api.generatedclasses.tables.Address;
import br.com.edfcbz.api.generatedclasses.tables.Availability;
import br.com.edfcbz.api.generatedclasses.tables.City;
import br.com.edfcbz.api.generatedclasses.tables.Country;
import br.com.edfcbz.api.generatedclasses.tables.Courrier;
import br.com.edfcbz.api.generatedclasses.tables.CourrierAvailability;
import br.com.edfcbz.api.generatedclasses.tables.CourrierHasNeighborhood;
import br.com.edfcbz.api.generatedclasses.tables.Cousine;
import br.com.edfcbz.api.generatedclasses.tables.Customer;
import br.com.edfcbz.api.generatedclasses.tables.CustomerHasAddress;
import br.com.edfcbz.api.generatedclasses.tables.Delivery;
import br.com.edfcbz.api.generatedclasses.tables.DeliveryHasStatusDeliveryDomain;
import br.com.edfcbz.api.generatedclasses.tables.Neighborhood;
import br.com.edfcbz.api.generatedclasses.tables.Order;
import br.com.edfcbz.api.generatedclasses.tables.OrderHasProduct;
import br.com.edfcbz.api.generatedclasses.tables.OrderHasStatus;
import br.com.edfcbz.api.generatedclasses.tables.OrderStatusDomain;
import br.com.edfcbz.api.generatedclasses.tables.OrderStore;
import br.com.edfcbz.api.generatedclasses.tables.Product;
import br.com.edfcbz.api.generatedclasses.tables.ProductHasStore;
import br.com.edfcbz.api.generatedclasses.tables.Province;
import br.com.edfcbz.api.generatedclasses.tables.StatusDeliveryDomain;
import br.com.edfcbz.api.generatedclasses.tables.StatusStore;
import br.com.edfcbz.api.generatedclasses.tables.Store;
import br.com.edfcbz.api.generatedclasses.tables.StoreHasAddress;
import br.com.edfcbz.api.generatedclasses.tables.StoreHasCousine;
import br.com.edfcbz.api.generatedclasses.tables.TypeAddress;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in apirest
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>apirest.address</code>.
     */
    public static final Address ADDRESS = br.com.edfcbz.api.generatedclasses.tables.Address.ADDRESS;

    /**
     * The table <code>apirest.availability</code>.
     */
    public static final Availability AVAILABILITY = br.com.edfcbz.api.generatedclasses.tables.Availability.AVAILABILITY;

    /**
     * The table <code>apirest.city</code>.
     */
    public static final City CITY = br.com.edfcbz.api.generatedclasses.tables.City.CITY;

    /**
     * The table <code>apirest.country</code>.
     */
    public static final Country COUNTRY = br.com.edfcbz.api.generatedclasses.tables.Country.COUNTRY;

    /**
     * The table <code>apirest.courrier</code>.
     */
    public static final Courrier COURRIER = br.com.edfcbz.api.generatedclasses.tables.Courrier.COURRIER;

    /**
     * The table <code>apirest.courrier_availability</code>.
     */
    public static final CourrierAvailability COURRIER_AVAILABILITY = br.com.edfcbz.api.generatedclasses.tables.CourrierAvailability.COURRIER_AVAILABILITY;

    /**
     * The table <code>apirest.courrier_has_neighborhood</code>.
     */
    public static final CourrierHasNeighborhood COURRIER_HAS_NEIGHBORHOOD = br.com.edfcbz.api.generatedclasses.tables.CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD;

    /**
     * The table <code>apirest.cousine</code>.
     */
    public static final Cousine COUSINE = br.com.edfcbz.api.generatedclasses.tables.Cousine.COUSINE;

    /**
     * The table <code>apirest.customer</code>.
     */
    public static final Customer CUSTOMER = br.com.edfcbz.api.generatedclasses.tables.Customer.CUSTOMER;

    /**
     * The table <code>apirest.customer_has_address</code>.
     */
    public static final CustomerHasAddress CUSTOMER_HAS_ADDRESS = br.com.edfcbz.api.generatedclasses.tables.CustomerHasAddress.CUSTOMER_HAS_ADDRESS;

    /**
     * The table <code>apirest.delivery</code>.
     */
    public static final Delivery DELIVERY = br.com.edfcbz.api.generatedclasses.tables.Delivery.DELIVERY;

    /**
     * The table <code>apirest.delivery_has_status_delivery_domain</code>.
     */
    public static final DeliveryHasStatusDeliveryDomain DELIVERY_HAS_STATUS_DELIVERY_DOMAIN = br.com.edfcbz.api.generatedclasses.tables.DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN;

    /**
     * The table <code>apirest.neighborhood</code>.
     */
    public static final Neighborhood NEIGHBORHOOD = br.com.edfcbz.api.generatedclasses.tables.Neighborhood.NEIGHBORHOOD;

    /**
     * The table <code>apirest.order</code>.
     */
    public static final Order ORDER = br.com.edfcbz.api.generatedclasses.tables.Order.ORDER;

    /**
     * The table <code>apirest.order_has_product</code>.
     */
    public static final OrderHasProduct ORDER_HAS_PRODUCT = br.com.edfcbz.api.generatedclasses.tables.OrderHasProduct.ORDER_HAS_PRODUCT;

    /**
     * The table <code>apirest.order_has_status</code>.
     */
    public static final OrderHasStatus ORDER_HAS_STATUS = br.com.edfcbz.api.generatedclasses.tables.OrderHasStatus.ORDER_HAS_STATUS;

    /**
     * The table <code>apirest.order_status_domain</code>.
     */
    public static final OrderStatusDomain ORDER_STATUS_DOMAIN = br.com.edfcbz.api.generatedclasses.tables.OrderStatusDomain.ORDER_STATUS_DOMAIN;

    /**
     * The table <code>apirest.order_store</code>.
     */
    public static final OrderStore ORDER_STORE = br.com.edfcbz.api.generatedclasses.tables.OrderStore.ORDER_STORE;

    /**
     * The table <code>apirest.product</code>.
     */
    public static final Product PRODUCT = br.com.edfcbz.api.generatedclasses.tables.Product.PRODUCT;

    /**
     * The table <code>apirest.product_has_store</code>.
     */
    public static final ProductHasStore PRODUCT_HAS_STORE = br.com.edfcbz.api.generatedclasses.tables.ProductHasStore.PRODUCT_HAS_STORE;

    /**
     * The table <code>apirest.province</code>.
     */
    public static final Province PROVINCE = br.com.edfcbz.api.generatedclasses.tables.Province.PROVINCE;

    /**
     * The table <code>apirest.status_delivery_domain</code>.
     */
    public static final StatusDeliveryDomain STATUS_DELIVERY_DOMAIN = br.com.edfcbz.api.generatedclasses.tables.StatusDeliveryDomain.STATUS_DELIVERY_DOMAIN;

    /**
     * The table <code>apirest.status_store</code>.
     */
    public static final StatusStore STATUS_STORE = br.com.edfcbz.api.generatedclasses.tables.StatusStore.STATUS_STORE;

    /**
     * The table <code>apirest.store</code>.
     */
    public static final Store STORE = br.com.edfcbz.api.generatedclasses.tables.Store.STORE;

    /**
     * The table <code>apirest.store_has_address</code>.
     */
    public static final StoreHasAddress STORE_HAS_ADDRESS = br.com.edfcbz.api.generatedclasses.tables.StoreHasAddress.STORE_HAS_ADDRESS;

    /**
     * The table <code>apirest.store_has_cousine</code>.
     */
    public static final StoreHasCousine STORE_HAS_COUSINE = br.com.edfcbz.api.generatedclasses.tables.StoreHasCousine.STORE_HAS_COUSINE;

    /**
     * The table <code>apirest.type_address</code>.
     */
    public static final TypeAddress TYPE_ADDRESS = br.com.edfcbz.api.generatedclasses.tables.TypeAddress.TYPE_ADDRESS;
}
