-- MySQL Script generated by MySQL Workbench
-- Tue Apr 13 10:16:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema apirest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apirest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apirest` DEFAULT CHARACTER SET utf8 ;
USE `apirest` ;

-- -----------------------------------------------------
-- Table `apirest`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `sigle` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 230
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`province` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `sigle` VARCHAR(5) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_province_country1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_province_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `apirest`.`country` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`id`, `province_id`, `name`),
  INDEX `fk_city_province1_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_province1`
    FOREIGN KEY (`province_id`)
    REFERENCES `apirest`.`province` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`neighborhood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`neighborhood` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `neighborhood` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `code` VARCHAR(15) NOT NULL,
  `referencePoint` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  `neighborhood_id` INT NOT NULL,
  PRIMARY KEY (`id`, `city_id`, `neighborhood_id`),
  INDEX `fk_address_city1_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_address_neighborhood1_idx` (`neighborhood_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `apirest`.`city` (`id`),
  CONSTRAINT `fk_address_neighborhood1`
    FOREIGN KEY (`neighborhood_id`)
    REFERENCES `apirest`.`neighborhood` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`availability` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `startAvailability` DATETIME NULL DEFAULT NULL,
  `finishAvailability` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`courrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`courrier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`, `address_id`),
  INDEX `fk_courrier_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_courrier_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `apirest`.`address` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`courrier_availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`courrier_availability` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courrier_id` INT NOT NULL,
  `availability_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_courrier_has_availability_availability1_idx` (`availability_id` ASC) VISIBLE,
  INDEX `fk_courrier_has_availability_courrier1_idx` (`courrier_id` ASC) VISIBLE,
  CONSTRAINT `fk_courrier_has_availability_availability1`
    FOREIGN KEY (`availability_id`)
    REFERENCES `apirest`.`availability` (`id`),
  CONSTRAINT `fk_courrier_has_availability_courrier1`
    FOREIGN KEY (`courrier_id`)
    REFERENCES `apirest`.`courrier` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`courrier_has_neighborhood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`courrier_has_neighborhood` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courrier_id` INT NOT NULL,
  `neighborhood_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_courrier_has_neighborhood_neighborhood1_idx` (`neighborhood_id` ASC) VISIBLE,
  INDEX `fk_courrier_has_neighborhood_courrier1_idx` (`courrier_id` ASC) VISIBLE,
  CONSTRAINT `fk_courrier_has_neighborhood_courrier1`
    FOREIGN KEY (`courrier_id`)
    REFERENCES `apirest`.`courrier` (`id`),
  CONSTRAINT `fk_courrier_has_neighborhood_neighborhood1`
    FOREIGN KEY (`neighborhood_id`)
    REFERENCES `apirest`.`neighborhood` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`cousine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`cousine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `creation` DATETIME NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`type_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`type_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`customer_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`customer_has_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_id` INT NOT NULL,
  `type_address_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_has_address_address1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_customer_has_address_type_address1_idx` (`type_address_id` ASC) VISIBLE,
  INDEX `fk_customer_has_address_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_has_address_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `apirest`.`address` (`id`),
  CONSTRAINT `fk_customer_has_address_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `apirest`.`customer` (`id`),
  CONSTRAINT `fk_customer_has_address_type_address1`
    FOREIGN KEY (`type_address_id`)
    REFERENCES `apirest`.`type_address` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`delivery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courrier_id` INT NOT NULL,
  `update` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_delivery_courrier1_idx` (`courrier_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_courrier1`
    FOREIGN KEY (`courrier_id`)
    REFERENCES `apirest`.`courrier` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10693
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`status_delivery_domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`status_delivery_domain` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`delivery_has_status_delivery_domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`delivery_has_status_delivery_domain` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `delivery_id` INT NOT NULL,
  `status_delivery_domain_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_delivery_has_status_delivery_domain_status_delivery_doma_idx` (`status_delivery_domain_id` ASC) VISIBLE,
  INDEX `fk_delivery_has_status_delivery_domain_delivery1_idx` (`delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_has_status_delivery_domain_delivery1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `apirest`.`delivery` (`id`),
  CONSTRAINT `fk_delivery_has_status_delivery_domain_status_delivery_domain1`
    FOREIGN KEY (`status_delivery_domain_id`)
    REFERENCES `apirest`.`status_delivery_domain` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  `delivery_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_order_customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_order_delivery1_idx` (`delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `apirest`.`customer` (`id`),
  CONSTRAINT `fk_order_delivery1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `apirest`.`delivery` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 90
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `productImage` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`order_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`order_has_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_order_has_product_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `apirest`.`order` (`id`),
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `apirest`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 202
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`order_status_domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`order_status_domain` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`order_has_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`order_has_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `order_status_domain_id` INT NOT NULL,
  `update` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_has_order_status_domain_order_status_domain1_idx` (`order_status_domain_id` ASC) VISIBLE,
  INDEX `fk_order_has_order_status_domain_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_order_status_domain_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `apirest`.`order` (`id`),
  CONSTRAINT `fk_order_has_order_status_domain_order_status_domain1`
    FOREIGN KEY (`order_status_domain_id`)
    REFERENCES `apirest`.`order_status_domain` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`status_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`status_store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `logo` BLOB NOT NULL,
  `deliveryFee` FLOAT NOT NULL,
  `deliveryFeeFreeOver` FLOAT NULL DEFAULT NULL,
  `status_store_id` INT NOT NULL,
  PRIMARY KEY (`id`, `status_store_id`),
  INDEX `fk_store_status_store1_idx` (`status_store_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_status_store1`
    FOREIGN KEY (`status_store_id`)
    REFERENCES `apirest`.`status_store` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`order_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`order_store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_has_store_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_has_store_store1_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_store_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `apirest`.`order` (`id`),
  CONSTRAINT `fk_order_has_store_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `apirest`.`store` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`product_has_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`product_has_store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_has_store_store1_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_product_has_store_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_store_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `apirest`.`product` (`id`),
  CONSTRAINT `fk_product_has_store_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `apirest`.`store` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`store_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`store_has_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_store_has_address_address1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_store_has_address_store1_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_has_address_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `apirest`.`address` (`id`),
  CONSTRAINT `fk_store_has_address_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `apirest`.`store` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apirest`.`store_has_cousine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apirest`.`store_has_cousine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `storeId` INT NOT NULL,
  `cousine_id` INT NOT NULL,
  `isMain` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_store_has_cousine_store1_idx` (`storeId` ASC) VISIBLE,
  INDEX `fk_store_has_cousine_cousine1_idx` (`cousine_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_has_cousine_cousine1`
    FOREIGN KEY (`cousine_id`)
    REFERENCES `apirest`.`cousine` (`id`),
  CONSTRAINT `fk_store_has_cousine_store1`
    FOREIGN KEY (`storeId`)
    REFERENCES `apirest`.`store` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
