/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables;


import br.com.edfcbz.api.generatedclasses.Apirest;
import br.com.edfcbz.api.generatedclasses.Indexes;
import br.com.edfcbz.api.generatedclasses.Keys;
import br.com.edfcbz.api.generatedclasses.tables.records.CourrierHasNeighborhoodRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourrierHasNeighborhood extends TableImpl<CourrierHasNeighborhoodRecord> {

    private static final long serialVersionUID = 354824621;

    /**
     * The reference instance of <code>apirest.courrier_has_neighborhood</code>
     */
    public static final CourrierHasNeighborhood COURRIER_HAS_NEIGHBORHOOD = new CourrierHasNeighborhood();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CourrierHasNeighborhoodRecord> getRecordType() {
        return CourrierHasNeighborhoodRecord.class;
    }

    /**
     * The column <code>apirest.courrier_has_neighborhood.id</code>.
     */
    public final TableField<CourrierHasNeighborhoodRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>apirest.courrier_has_neighborhood.courrier_id</code>.
     */
    public final TableField<CourrierHasNeighborhoodRecord, Integer> COURRIER_ID = createField("courrier_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>apirest.courrier_has_neighborhood.neighborhood_id</code>.
     */
    public final TableField<CourrierHasNeighborhoodRecord, Integer> NEIGHBORHOOD_ID = createField("neighborhood_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>apirest.courrier_has_neighborhood</code> table reference
     */
    public CourrierHasNeighborhood() {
        this(DSL.name("courrier_has_neighborhood"), null);
    }

    /**
     * Create an aliased <code>apirest.courrier_has_neighborhood</code> table reference
     */
    public CourrierHasNeighborhood(String alias) {
        this(DSL.name(alias), COURRIER_HAS_NEIGHBORHOOD);
    }

    /**
     * Create an aliased <code>apirest.courrier_has_neighborhood</code> table reference
     */
    public CourrierHasNeighborhood(Name alias) {
        this(alias, COURRIER_HAS_NEIGHBORHOOD);
    }

    private CourrierHasNeighborhood(Name alias, Table<CourrierHasNeighborhoodRecord> aliased) {
        this(alias, aliased, null);
    }

    private CourrierHasNeighborhood(Name alias, Table<CourrierHasNeighborhoodRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Apirest.APIREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COURRIER_HAS_NEIGHBORHOOD_FK_COURRIER_HAS_NEIGHBORHOOD_COURRIER1_IDX, Indexes.COURRIER_HAS_NEIGHBORHOOD_FK_COURRIER_HAS_NEIGHBORHOOD_NEIGHBORHOOD1_IDX, Indexes.COURRIER_HAS_NEIGHBORHOOD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CourrierHasNeighborhoodRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COURRIER_HAS_NEIGHBORHOOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CourrierHasNeighborhoodRecord> getPrimaryKey() {
        return Keys.KEY_COURRIER_HAS_NEIGHBORHOOD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CourrierHasNeighborhoodRecord>> getKeys() {
        return Arrays.<UniqueKey<CourrierHasNeighborhoodRecord>>asList(Keys.KEY_COURRIER_HAS_NEIGHBORHOOD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CourrierHasNeighborhoodRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CourrierHasNeighborhoodRecord, ?>>asList(Keys.FK_COURRIER_HAS_NEIGHBORHOOD_COURRIER1, Keys.FK_COURRIER_HAS_NEIGHBORHOOD_NEIGHBORHOOD1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourrierHasNeighborhood as(String alias) {
        return new CourrierHasNeighborhood(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourrierHasNeighborhood as(Name alias) {
        return new CourrierHasNeighborhood(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CourrierHasNeighborhood rename(String name) {
        return new CourrierHasNeighborhood(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CourrierHasNeighborhood rename(Name name) {
        return new CourrierHasNeighborhood(name, null);
    }
}
