/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables;


import br.com.edfcbz.api.generatedclasses.Apirest;
import br.com.edfcbz.api.generatedclasses.Indexes;
import br.com.edfcbz.api.generatedclasses.Keys;
import br.com.edfcbz.api.generatedclasses.tables.records.CourrierAvailabilityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourrierAvailability extends TableImpl<CourrierAvailabilityRecord> {

    private static final long serialVersionUID = -1805199323;

    /**
     * The reference instance of <code>apirest.courrier_availability</code>
     */
    public static final CourrierAvailability COURRIER_AVAILABILITY = new CourrierAvailability();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CourrierAvailabilityRecord> getRecordType() {
        return CourrierAvailabilityRecord.class;
    }

    /**
     * The column <code>apirest.courrier_availability.id</code>.
     */
    public final TableField<CourrierAvailabilityRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>apirest.courrier_availability.courrier_id</code>.
     */
    public final TableField<CourrierAvailabilityRecord, Integer> COURRIER_ID = createField("courrier_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>apirest.courrier_availability.availability_id</code>.
     */
    public final TableField<CourrierAvailabilityRecord, Integer> AVAILABILITY_ID = createField("availability_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>apirest.courrier_availability</code> table reference
     */
    public CourrierAvailability() {
        this(DSL.name("courrier_availability"), null);
    }

    /**
     * Create an aliased <code>apirest.courrier_availability</code> table reference
     */
    public CourrierAvailability(String alias) {
        this(DSL.name(alias), COURRIER_AVAILABILITY);
    }

    /**
     * Create an aliased <code>apirest.courrier_availability</code> table reference
     */
    public CourrierAvailability(Name alias) {
        this(alias, COURRIER_AVAILABILITY);
    }

    private CourrierAvailability(Name alias, Table<CourrierAvailabilityRecord> aliased) {
        this(alias, aliased, null);
    }

    private CourrierAvailability(Name alias, Table<CourrierAvailabilityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Apirest.APIREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COURRIER_AVAILABILITY_FK_COURRIER_HAS_AVAILABILITY_AVAILABILITY1_IDX, Indexes.COURRIER_AVAILABILITY_FK_COURRIER_HAS_AVAILABILITY_COURRIER1_IDX, Indexes.COURRIER_AVAILABILITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CourrierAvailabilityRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COURRIER_AVAILABILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CourrierAvailabilityRecord> getPrimaryKey() {
        return Keys.KEY_COURRIER_AVAILABILITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CourrierAvailabilityRecord>> getKeys() {
        return Arrays.<UniqueKey<CourrierAvailabilityRecord>>asList(Keys.KEY_COURRIER_AVAILABILITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CourrierAvailabilityRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CourrierAvailabilityRecord, ?>>asList(Keys.FK_COURRIER_HAS_AVAILABILITY_COURRIER1, Keys.FK_COURRIER_HAS_AVAILABILITY_AVAILABILITY1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourrierAvailability as(String alias) {
        return new CourrierAvailability(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourrierAvailability as(Name alias) {
        return new CourrierAvailability(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CourrierAvailability rename(String name) {
        return new CourrierAvailability(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CourrierAvailability rename(Name name) {
        return new CourrierAvailability(name, null);
    }
}
