/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables;


import br.com.edfcbz.api.generatedclasses.Apirest;
import br.com.edfcbz.api.generatedclasses.Indexes;
import br.com.edfcbz.api.generatedclasses.Keys;
import br.com.edfcbz.api.generatedclasses.tables.records.CousineRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cousine extends TableImpl<CousineRecord> {

    private static final long serialVersionUID = -1955374539;

    /**
     * The reference instance of <code>apirest.cousine</code>
     */
    public static final Cousine COUSINE = new Cousine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CousineRecord> getRecordType() {
        return CousineRecord.class;
    }

    /**
     * The column <code>apirest.cousine.id</code>.
     */
    public final TableField<CousineRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>apirest.cousine.name</code>.
     */
    public final TableField<CousineRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * Create a <code>apirest.cousine</code> table reference
     */
    public Cousine() {
        this(DSL.name("cousine"), null);
    }

    /**
     * Create an aliased <code>apirest.cousine</code> table reference
     */
    public Cousine(String alias) {
        this(DSL.name(alias), COUSINE);
    }

    /**
     * Create an aliased <code>apirest.cousine</code> table reference
     */
    public Cousine(Name alias) {
        this(alias, COUSINE);
    }

    private Cousine(Name alias, Table<CousineRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cousine(Name alias, Table<CousineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Apirest.APIREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COUSINE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CousineRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COUSINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CousineRecord> getPrimaryKey() {
        return Keys.KEY_COUSINE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CousineRecord>> getKeys() {
        return Arrays.<UniqueKey<CousineRecord>>asList(Keys.KEY_COUSINE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cousine as(String alias) {
        return new Cousine(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cousine as(Name alias) {
        return new Cousine(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cousine rename(String name) {
        return new Cousine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cousine rename(Name name) {
        return new Cousine(name, null);
    }
}
