/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables;


import br.com.edfcbz.api.generatedclasses.Apirest;
import br.com.edfcbz.api.generatedclasses.Indexes;
import br.com.edfcbz.api.generatedclasses.Keys;
import br.com.edfcbz.api.generatedclasses.tables.records.DeliveryHasStatusDeliveryDomainRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryHasStatusDeliveryDomain extends TableImpl<DeliveryHasStatusDeliveryDomainRecord> {

    private static final long serialVersionUID = 3275558;

    /**
     * The reference instance of <code>apirest.delivery_has_status_delivery_domain</code>
     */
    public static final DeliveryHasStatusDeliveryDomain DELIVERY_HAS_STATUS_DELIVERY_DOMAIN = new DeliveryHasStatusDeliveryDomain();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeliveryHasStatusDeliveryDomainRecord> getRecordType() {
        return DeliveryHasStatusDeliveryDomainRecord.class;
    }

    /**
     * The column <code>apirest.delivery_has_status_delivery_domain.id</code>.
     */
    public final TableField<DeliveryHasStatusDeliveryDomainRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>apirest.delivery_has_status_delivery_domain.delivery_id</code>.
     */
    public final TableField<DeliveryHasStatusDeliveryDomainRecord, Integer> DELIVERY_ID = createField("delivery_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>apirest.delivery_has_status_delivery_domain.status_delivery_domain_id</code>.
     */
    public final TableField<DeliveryHasStatusDeliveryDomainRecord, Integer> STATUS_DELIVERY_DOMAIN_ID = createField("status_delivery_domain_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>apirest.delivery_has_status_delivery_domain</code> table reference
     */
    public DeliveryHasStatusDeliveryDomain() {
        this(DSL.name("delivery_has_status_delivery_domain"), null);
    }

    /**
     * Create an aliased <code>apirest.delivery_has_status_delivery_domain</code> table reference
     */
    public DeliveryHasStatusDeliveryDomain(String alias) {
        this(DSL.name(alias), DELIVERY_HAS_STATUS_DELIVERY_DOMAIN);
    }

    /**
     * Create an aliased <code>apirest.delivery_has_status_delivery_domain</code> table reference
     */
    public DeliveryHasStatusDeliveryDomain(Name alias) {
        this(alias, DELIVERY_HAS_STATUS_DELIVERY_DOMAIN);
    }

    private DeliveryHasStatusDeliveryDomain(Name alias, Table<DeliveryHasStatusDeliveryDomainRecord> aliased) {
        this(alias, aliased, null);
    }

    private DeliveryHasStatusDeliveryDomain(Name alias, Table<DeliveryHasStatusDeliveryDomainRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Apirest.APIREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_FK_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_DELIVERY1_IDX, Indexes.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_FK_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_STATUS_DELIVERY_DOMA_IDX, Indexes.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DeliveryHasStatusDeliveryDomainRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DeliveryHasStatusDeliveryDomainRecord> getPrimaryKey() {
        return Keys.KEY_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DeliveryHasStatusDeliveryDomainRecord>> getKeys() {
        return Arrays.<UniqueKey<DeliveryHasStatusDeliveryDomainRecord>>asList(Keys.KEY_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DeliveryHasStatusDeliveryDomainRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DeliveryHasStatusDeliveryDomainRecord, ?>>asList(Keys.FK_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_DELIVERY1, Keys.FK_DELIVERY_HAS_STATUS_DELIVERY_DOMAIN_STATUS_DELIVERY_DOMAIN1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryHasStatusDeliveryDomain as(String alias) {
        return new DeliveryHasStatusDeliveryDomain(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryHasStatusDeliveryDomain as(Name alias) {
        return new DeliveryHasStatusDeliveryDomain(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DeliveryHasStatusDeliveryDomain rename(String name) {
        return new DeliveryHasStatusDeliveryDomain(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DeliveryHasStatusDeliveryDomain rename(Name name) {
        return new DeliveryHasStatusDeliveryDomain(name, null);
    }
}
