/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables;


import br.com.edfcbz.api.generatedclasses.Apirest;
import br.com.edfcbz.api.generatedclasses.Indexes;
import br.com.edfcbz.api.generatedclasses.Keys;
import br.com.edfcbz.api.generatedclasses.tables.records.OrderHasProductRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderHasProduct extends TableImpl<OrderHasProductRecord> {

    private static final long serialVersionUID = 85823029;

    /**
     * The reference instance of <code>apirest.order_has_product</code>
     */
    public static final OrderHasProduct ORDER_HAS_PRODUCT = new OrderHasProduct();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderHasProductRecord> getRecordType() {
        return OrderHasProductRecord.class;
    }

    /**
     * The column <code>apirest.order_has_product.id</code>.
     */
    public final TableField<OrderHasProductRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>apirest.order_has_product.order_id</code>.
     */
    public final TableField<OrderHasProductRecord, Integer> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>apirest.order_has_product.product_id</code>.
     */
    public final TableField<OrderHasProductRecord, Integer> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>apirest.order_has_product.quantity</code>.
     */
    public final TableField<OrderHasProductRecord, Integer> QUANTITY = createField("quantity", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>apirest.order_has_product</code> table reference
     */
    public OrderHasProduct() {
        this(DSL.name("order_has_product"), null);
    }

    /**
     * Create an aliased <code>apirest.order_has_product</code> table reference
     */
    public OrderHasProduct(String alias) {
        this(DSL.name(alias), ORDER_HAS_PRODUCT);
    }

    /**
     * Create an aliased <code>apirest.order_has_product</code> table reference
     */
    public OrderHasProduct(Name alias) {
        this(alias, ORDER_HAS_PRODUCT);
    }

    private OrderHasProduct(Name alias, Table<OrderHasProductRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderHasProduct(Name alias, Table<OrderHasProductRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Apirest.APIREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ORDER_HAS_PRODUCT_FK_ORDER_HAS_PRODUCT_ORDER1_IDX, Indexes.ORDER_HAS_PRODUCT_FK_ORDER_HAS_PRODUCT_PRODUCT1_IDX, Indexes.ORDER_HAS_PRODUCT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrderHasProductRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORDER_HAS_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrderHasProductRecord> getPrimaryKey() {
        return Keys.KEY_ORDER_HAS_PRODUCT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrderHasProductRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderHasProductRecord>>asList(Keys.KEY_ORDER_HAS_PRODUCT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrderHasProductRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrderHasProductRecord, ?>>asList(Keys.FK_ORDER_HAS_PRODUCT_ORDER1, Keys.FK_ORDER_HAS_PRODUCT_PRODUCT1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderHasProduct as(String alias) {
        return new OrderHasProduct(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderHasProduct as(Name alias) {
        return new OrderHasProduct(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderHasProduct rename(String name) {
        return new OrderHasProduct(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderHasProduct rename(Name name) {
        return new OrderHasProduct(name, null);
    }
}
