/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables;


import br.com.edfcbz.api.generatedclasses.Apirest;
import br.com.edfcbz.api.generatedclasses.Indexes;
import br.com.edfcbz.api.generatedclasses.Keys;
import br.com.edfcbz.api.generatedclasses.tables.records.OrderStatusDomainRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderStatusDomain extends TableImpl<OrderStatusDomainRecord> {

    private static final long serialVersionUID = -1478375154;

    /**
     * The reference instance of <code>apirest.order_status_domain</code>
     */
    public static final OrderStatusDomain ORDER_STATUS_DOMAIN = new OrderStatusDomain();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderStatusDomainRecord> getRecordType() {
        return OrderStatusDomainRecord.class;
    }

    /**
     * The column <code>apirest.order_status_domain.id</code>.
     */
    public final TableField<OrderStatusDomainRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>apirest.order_status_domain.name</code>.
     */
    public final TableField<OrderStatusDomainRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * Create a <code>apirest.order_status_domain</code> table reference
     */
    public OrderStatusDomain() {
        this(DSL.name("order_status_domain"), null);
    }

    /**
     * Create an aliased <code>apirest.order_status_domain</code> table reference
     */
    public OrderStatusDomain(String alias) {
        this(DSL.name(alias), ORDER_STATUS_DOMAIN);
    }

    /**
     * Create an aliased <code>apirest.order_status_domain</code> table reference
     */
    public OrderStatusDomain(Name alias) {
        this(alias, ORDER_STATUS_DOMAIN);
    }

    private OrderStatusDomain(Name alias, Table<OrderStatusDomainRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderStatusDomain(Name alias, Table<OrderStatusDomainRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Apirest.APIREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ORDER_STATUS_DOMAIN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrderStatusDomainRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORDER_STATUS_DOMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrderStatusDomainRecord> getPrimaryKey() {
        return Keys.KEY_ORDER_STATUS_DOMAIN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrderStatusDomainRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderStatusDomainRecord>>asList(Keys.KEY_ORDER_STATUS_DOMAIN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderStatusDomain as(String alias) {
        return new OrderStatusDomain(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderStatusDomain as(Name alias) {
        return new OrderStatusDomain(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderStatusDomain rename(String name) {
        return new OrderStatusDomain(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderStatusDomain rename(Name name) {
        return new OrderStatusDomain(name, null);
    }
}
