/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables;


import br.com.edfcbz.api.generatedclasses.Apirest;
import br.com.edfcbz.api.generatedclasses.Indexes;
import br.com.edfcbz.api.generatedclasses.Keys;
import br.com.edfcbz.api.generatedclasses.tables.records.StatusStoreRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusStore extends TableImpl<StatusStoreRecord> {

    private static final long serialVersionUID = 139820592;

    /**
     * The reference instance of <code>apirest.status_store</code>
     */
    public static final StatusStore STATUS_STORE = new StatusStore();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StatusStoreRecord> getRecordType() {
        return StatusStoreRecord.class;
    }

    /**
     * The column <code>apirest.status_store.id</code>.
     */
    public final TableField<StatusStoreRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>apirest.status_store.status</code>.
     */
    public final TableField<StatusStoreRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * Create a <code>apirest.status_store</code> table reference
     */
    public StatusStore() {
        this(DSL.name("status_store"), null);
    }

    /**
     * Create an aliased <code>apirest.status_store</code> table reference
     */
    public StatusStore(String alias) {
        this(DSL.name(alias), STATUS_STORE);
    }

    /**
     * Create an aliased <code>apirest.status_store</code> table reference
     */
    public StatusStore(Name alias) {
        this(alias, STATUS_STORE);
    }

    private StatusStore(Name alias, Table<StatusStoreRecord> aliased) {
        this(alias, aliased, null);
    }

    private StatusStore(Name alias, Table<StatusStoreRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Apirest.APIREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STATUS_STORE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StatusStoreRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STATUS_STORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StatusStoreRecord> getPrimaryKey() {
        return Keys.KEY_STATUS_STORE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StatusStoreRecord>> getKeys() {
        return Arrays.<UniqueKey<StatusStoreRecord>>asList(Keys.KEY_STATUS_STORE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusStore as(String alias) {
        return new StatusStore(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusStore as(Name alias) {
        return new StatusStore(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StatusStore rename(String name) {
        return new StatusStore(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StatusStore rename(Name name) {
        return new StatusStore(name, null);
    }
}
