/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables;


import br.com.edfcbz.api.generatedclasses.Apirest;
import br.com.edfcbz.api.generatedclasses.Indexes;
import br.com.edfcbz.api.generatedclasses.Keys;
import br.com.edfcbz.api.generatedclasses.tables.records.StoreHasAddressRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreHasAddress extends TableImpl<StoreHasAddressRecord> {

    private static final long serialVersionUID = 1954896435;

    /**
     * The reference instance of <code>apirest.store_has_address</code>
     */
    public static final StoreHasAddress STORE_HAS_ADDRESS = new StoreHasAddress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoreHasAddressRecord> getRecordType() {
        return StoreHasAddressRecord.class;
    }

    /**
     * The column <code>apirest.store_has_address.id</code>.
     */
    public final TableField<StoreHasAddressRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>apirest.store_has_address.store_id</code>.
     */
    public final TableField<StoreHasAddressRecord, Integer> STORE_ID = createField("store_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>apirest.store_has_address.address_id</code>.
     */
    public final TableField<StoreHasAddressRecord, Integer> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>apirest.store_has_address</code> table reference
     */
    public StoreHasAddress() {
        this(DSL.name("store_has_address"), null);
    }

    /**
     * Create an aliased <code>apirest.store_has_address</code> table reference
     */
    public StoreHasAddress(String alias) {
        this(DSL.name(alias), STORE_HAS_ADDRESS);
    }

    /**
     * Create an aliased <code>apirest.store_has_address</code> table reference
     */
    public StoreHasAddress(Name alias) {
        this(alias, STORE_HAS_ADDRESS);
    }

    private StoreHasAddress(Name alias, Table<StoreHasAddressRecord> aliased) {
        this(alias, aliased, null);
    }

    private StoreHasAddress(Name alias, Table<StoreHasAddressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Apirest.APIREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STORE_HAS_ADDRESS_FK_STORE_HAS_ADDRESS_ADDRESS1_IDX, Indexes.STORE_HAS_ADDRESS_FK_STORE_HAS_ADDRESS_STORE1_IDX, Indexes.STORE_HAS_ADDRESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StoreHasAddressRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STORE_HAS_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StoreHasAddressRecord> getPrimaryKey() {
        return Keys.KEY_STORE_HAS_ADDRESS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StoreHasAddressRecord>> getKeys() {
        return Arrays.<UniqueKey<StoreHasAddressRecord>>asList(Keys.KEY_STORE_HAS_ADDRESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StoreHasAddressRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StoreHasAddressRecord, ?>>asList(Keys.FK_STORE_HAS_ADDRESS_STORE1, Keys.FK_STORE_HAS_ADDRESS_ADDRESS1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoreHasAddress as(String alias) {
        return new StoreHasAddress(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoreHasAddress as(Name alias) {
        return new StoreHasAddress(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreHasAddress rename(String name) {
        return new StoreHasAddress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreHasAddress rename(Name name) {
        return new StoreHasAddress(name, null);
    }
}
