/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables;


import br.com.edfcbz.api.generatedclasses.Apirest;
import br.com.edfcbz.api.generatedclasses.Indexes;
import br.com.edfcbz.api.generatedclasses.Keys;
import br.com.edfcbz.api.generatedclasses.tables.records.TypeAddressRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeAddress extends TableImpl<TypeAddressRecord> {

    private static final long serialVersionUID = -1988879837;

    /**
     * The reference instance of <code>apirest.type_address</code>
     */
    public static final TypeAddress TYPE_ADDRESS = new TypeAddress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TypeAddressRecord> getRecordType() {
        return TypeAddressRecord.class;
    }

    /**
     * The column <code>apirest.type_address.id</code>.
     */
    public final TableField<TypeAddressRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>apirest.type_address.description_type</code>.
     */
    public final TableField<TypeAddressRecord, String> DESCRIPTION_TYPE = createField("description_type", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * Create a <code>apirest.type_address</code> table reference
     */
    public TypeAddress() {
        this(DSL.name("type_address"), null);
    }

    /**
     * Create an aliased <code>apirest.type_address</code> table reference
     */
    public TypeAddress(String alias) {
        this(DSL.name(alias), TYPE_ADDRESS);
    }

    /**
     * Create an aliased <code>apirest.type_address</code> table reference
     */
    public TypeAddress(Name alias) {
        this(alias, TYPE_ADDRESS);
    }

    private TypeAddress(Name alias, Table<TypeAddressRecord> aliased) {
        this(alias, aliased, null);
    }

    private TypeAddress(Name alias, Table<TypeAddressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Apirest.APIREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TYPE_ADDRESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TypeAddressRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TYPE_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TypeAddressRecord> getPrimaryKey() {
        return Keys.KEY_TYPE_ADDRESS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TypeAddressRecord>> getKeys() {
        return Arrays.<UniqueKey<TypeAddressRecord>>asList(Keys.KEY_TYPE_ADDRESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeAddress as(String alias) {
        return new TypeAddress(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeAddress as(Name alias) {
        return new TypeAddress(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TypeAddress rename(String name) {
        return new TypeAddress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TypeAddress rename(Name name) {
        return new TypeAddress(name, null);
    }
}
