/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables.records;


import br.com.edfcbz.api.generatedclasses.tables.Availability;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvailabilityRecord extends UpdatableRecordImpl<AvailabilityRecord> implements Record3<Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1828844391;

    /**
     * Setter for <code>apirest.availability.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apirest.availability.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apirest.availability.startAvailability</code>.
     */
    public void setStartavailability(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>apirest.availability.startAvailability</code>.
     */
    public Timestamp getStartavailability() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>apirest.availability.finishAvailability</code>.
     */
    public void setFinishavailability(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>apirest.availability.finishAvailability</code>.
     */
    public Timestamp getFinishavailability() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Timestamp, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Availability.AVAILABILITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Availability.AVAILABILITY.STARTAVAILABILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Availability.AVAILABILITY.FINISHAVAILABILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getStartavailability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getFinishavailability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getStartavailability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getFinishavailability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilityRecord value2(Timestamp value) {
        setStartavailability(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilityRecord value3(Timestamp value) {
        setFinishavailability(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilityRecord values(Integer value1, Timestamp value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AvailabilityRecord
     */
    public AvailabilityRecord() {
        super(Availability.AVAILABILITY);
    }

    /**
     * Create a detached, initialised AvailabilityRecord
     */
    public AvailabilityRecord(Integer id, Timestamp startavailability, Timestamp finishavailability) {
        super(Availability.AVAILABILITY);

        set(0, id);
        set(1, startavailability);
        set(2, finishavailability);
    }
}
