/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables.records;


import br.com.edfcbz.api.generatedclasses.tables.CourrierHasNeighborhood;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourrierHasNeighborhoodRecord extends UpdatableRecordImpl<CourrierHasNeighborhoodRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -195270953;

    /**
     * Setter for <code>apirest.courrier_has_neighborhood.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apirest.courrier_has_neighborhood.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apirest.courrier_has_neighborhood.courrier_id</code>.
     */
    public void setCourrierId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>apirest.courrier_has_neighborhood.courrier_id</code>.
     */
    public Integer getCourrierId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>apirest.courrier_has_neighborhood.neighborhood_id</code>.
     */
    public void setNeighborhoodId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>apirest.courrier_has_neighborhood.neighborhood_id</code>.
     */
    public Integer getNeighborhoodId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD.COURRIER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD.NEIGHBORHOOD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCourrierId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getNeighborhoodId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCourrierId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNeighborhoodId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourrierHasNeighborhoodRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourrierHasNeighborhoodRecord value2(Integer value) {
        setCourrierId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourrierHasNeighborhoodRecord value3(Integer value) {
        setNeighborhoodId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourrierHasNeighborhoodRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourrierHasNeighborhoodRecord
     */
    public CourrierHasNeighborhoodRecord() {
        super(CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD);
    }

    /**
     * Create a detached, initialised CourrierHasNeighborhoodRecord
     */
    public CourrierHasNeighborhoodRecord(Integer id, Integer courrierId, Integer neighborhoodId) {
        super(CourrierHasNeighborhood.COURRIER_HAS_NEIGHBORHOOD);

        set(0, id);
        set(1, courrierId);
        set(2, neighborhoodId);
    }
}
