/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables.records;


import br.com.edfcbz.api.generatedclasses.tables.DeliveryHasStatusDeliveryDomain;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryHasStatusDeliveryDomainRecord extends UpdatableRecordImpl<DeliveryHasStatusDeliveryDomainRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 728468984;

    /**
     * Setter for <code>apirest.delivery_has_status_delivery_domain.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apirest.delivery_has_status_delivery_domain.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apirest.delivery_has_status_delivery_domain.delivery_id</code>.
     */
    public void setDeliveryId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>apirest.delivery_has_status_delivery_domain.delivery_id</code>.
     */
    public Integer getDeliveryId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>apirest.delivery_has_status_delivery_domain.status_delivery_domain_id</code>.
     */
    public void setStatusDeliveryDomainId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>apirest.delivery_has_status_delivery_domain.status_delivery_domain_id</code>.
     */
    public Integer getStatusDeliveryDomainId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN.DELIVERY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN.STATUS_DELIVERY_DOMAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDeliveryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getStatusDeliveryDomainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDeliveryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getStatusDeliveryDomainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryHasStatusDeliveryDomainRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryHasStatusDeliveryDomainRecord value2(Integer value) {
        setDeliveryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryHasStatusDeliveryDomainRecord value3(Integer value) {
        setStatusDeliveryDomainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeliveryHasStatusDeliveryDomainRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeliveryHasStatusDeliveryDomainRecord
     */
    public DeliveryHasStatusDeliveryDomainRecord() {
        super(DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN);
    }

    /**
     * Create a detached, initialised DeliveryHasStatusDeliveryDomainRecord
     */
    public DeliveryHasStatusDeliveryDomainRecord(Integer id, Integer deliveryId, Integer statusDeliveryDomainId) {
        super(DeliveryHasStatusDeliveryDomain.DELIVERY_HAS_STATUS_DELIVERY_DOMAIN);

        set(0, id);
        set(1, deliveryId);
        set(2, statusDeliveryDomainId);
    }
}
