/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables.records;


import br.com.edfcbz.api.generatedclasses.tables.Province;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinceRecord extends UpdatableRecordImpl<ProvinceRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = -1370689930;

    /**
     * Setter for <code>apirest.province.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apirest.province.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apirest.province.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>apirest.province.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>apirest.province.sigle</code>.
     */
    public void setSigle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>apirest.province.sigle</code>.
     */
    public String getSigle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>apirest.province.country_id</code>.
     */
    public void setCountryId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>apirest.province.country_id</code>.
     */
    public Integer getCountryId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Province.PROVINCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Province.PROVINCE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Province.PROVINCE.SIGLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Province.PROVINCE.COUNTRY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSigle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCountryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSigle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCountryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceRecord value3(String value) {
        setSigle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceRecord value4(Integer value) {
        setCountryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProvinceRecord
     */
    public ProvinceRecord() {
        super(Province.PROVINCE);
    }

    /**
     * Create a detached, initialised ProvinceRecord
     */
    public ProvinceRecord(Integer id, String name, String sigle, Integer countryId) {
        super(Province.PROVINCE);

        set(0, id);
        set(1, name);
        set(2, sigle);
        set(3, countryId);
    }
}
