/*
 * This file is generated by jOOQ.
*/
package br.com.edfcbz.api.generatedclasses.tables.records;


import br.com.edfcbz.api.generatedclasses.tables.StoreHasCousine;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreHasCousineRecord extends UpdatableRecordImpl<StoreHasCousineRecord> implements Record4<Integer, Integer, Integer, Byte> {

    private static final long serialVersionUID = -566077132;

    /**
     * Setter for <code>apirest.store_has_cousine.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>apirest.store_has_cousine.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>apirest.store_has_cousine.storeId</code>.
     */
    public void setStoreid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>apirest.store_has_cousine.storeId</code>.
     */
    public Integer getStoreid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>apirest.store_has_cousine.cousine_id</code>.
     */
    public void setCousineId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>apirest.store_has_cousine.cousine_id</code>.
     */
    public Integer getCousineId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>apirest.store_has_cousine.isMain</code>.
     */
    public void setIsmain(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>apirest.store_has_cousine.isMain</code>.
     */
    public Byte getIsmain() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Byte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Byte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StoreHasCousine.STORE_HAS_COUSINE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return StoreHasCousine.STORE_HAS_COUSINE.STOREID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return StoreHasCousine.STORE_HAS_COUSINE.COUSINE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return StoreHasCousine.STORE_HAS_COUSINE.ISMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getStoreid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCousineId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getIsmain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStoreid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCousineId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getIsmain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoreHasCousineRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoreHasCousineRecord value2(Integer value) {
        setStoreid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoreHasCousineRecord value3(Integer value) {
        setCousineId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoreHasCousineRecord value4(Byte value) {
        setIsmain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoreHasCousineRecord values(Integer value1, Integer value2, Integer value3, Byte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreHasCousineRecord
     */
    public StoreHasCousineRecord() {
        super(StoreHasCousine.STORE_HAS_COUSINE);
    }

    /**
     * Create a detached, initialised StoreHasCousineRecord
     */
    public StoreHasCousineRecord(Integer id, Integer storeid, Integer cousineId, Byte ismain) {
        super(StoreHasCousine.STORE_HAS_COUSINE);

        set(0, id);
        set(1, storeid);
        set(2, cousineId);
        set(3, ismain);
    }
}
